gui:
  theme:
    activeBorderColor:
      - '#7aa2f7'
      - bold
    inactiveBorderColor:
      - '#3b4261'
    optionsTextColor:
      - '#7aa2f7'
    selectedLineBgColor:
      - '#283457'
    selectedRangeBgColor:
      - '#283457'
    cherryPickedCommitBgColor:
      - '#7aa2f7'
    cherryPickedCommitFgColor:
      - '#7aa2f7'
    unstagedChangesColor:
      - '#f7768e'
    defaultFgColor:
      - '#c0caf5'
    searchingActiveBorderColor:
      - '#e0af68'